//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlizzTV.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlizzTV.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap blizztv_16 {
            get {
                object obj = ResourceManager.GetObject("blizztv_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap event_16 {
            get {
                object obj = ResourceManager.GetObject("event_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap feed_16 {
            get {
                object obj = ResourceManager.GetObject("feed_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon ico_blizztv_16 {
            get {
                object obj = ResourceManager.GetObject("ico_blizztv_16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ico_sleep_16 {
            get {
                object obj = ResourceManager.GetObject("ico_sleep_16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Providers xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Provider xsi:type=&quot;Stream&quot; Name=&quot;LiveStream&quot; Movie=&quot;http://cdn.livestream.com/grid/LSPlayer.swf&quot; FlashVars=&quot;channel=%slug%&amp;amp;autoPlay=true&quot; ChatMovie=&quot;http://cdn.livestream.com/chat/LivestreamChat.swf?&amp;amp;showTimestamp=true&amp;amp;channel=%slug%&quot; /&gt;
        ///  &lt;Provider xsi:type=&quot;Stream&quot; Name=&quot;UStream&quot; Movie=&quot;http://www.ustream.tv/flash/live/1/%stream_id%?v3=1&quot; FlashVars=&quot;autopla [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Providers {
            get {
                return ResourceManager.GetString("Providers", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap stream_16 {
            get {
                object obj = ResourceManager.GetObject("stream_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Subscriptions xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Subscription xsi:type=&quot;Feed&quot; Name=&quot;BlizzTV&quot; Url=&quot;http://www.blizztv.com/rss/ccs/1-blizztvcom/&quot; /&gt;
        ///  &lt;Subscription xsi:type=&quot;Feed&quot; Name=&quot;TeamLiquid&quot; Url=&quot;http://www.teamliquid.net/rss/news.xml&quot; /&gt;
        ///  &lt;Subscription xsi:type=&quot;Feed&quot; Name=&quot;GosuGamers&quot; Url=&quot;http://www.gosugamers.net/starcraft2/sc2.rss&quot; /&gt;
        ///  &lt;Subscription xsi:type=&quot;Feed&quot; Name=&quot;SCArmory&quot; Url=&quot;http://feeds.f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Subscriptions_Default {
            get {
                return ResourceManager.GetString("Subscriptions_Default", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap video_16 {
            get {
                object obj = ResourceManager.GetObject("video_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
