//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlizzTV.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlizzTV.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap blizzblues_16 {
            get {
                object obj = ResourceManager.GetObject("blizzblues_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap blizztv_16 {
            get {
                object obj = ResourceManager.GetObject("blizztv_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap calendar_16 {
            get {
                object obj = ResourceManager.GetObject("calendar_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eu_16 {
            get {
                object obj = ResourceManager.GetObject("eu_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap event_16 {
            get {
                object obj = ResourceManager.GetObject("event_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap feed_16 {
            get {
                object obj = ResourceManager.GetObject("feed_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon ico_blizztv_16 {
            get {
                object obj = ResourceManager.GetObject("ico_blizztv_16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ico_sleep_16 {
            get {
                object obj = ResourceManager.GetObject("ico_sleep_16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Providers xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Provider xsi:type=&quot;Stream&quot; Name=&quot;LiveStream&quot; Movie=&quot;http://cdn.livestream.com/grid/LSPlayer.swf&quot; FlashVars=&quot;channel=%slug%&amp;amp;autoPlay=true&quot; ChatMovie=&quot;http://cdn.livestream.com/chat/LivestreamChat.swf?&amp;amp;showTimestamp=true&amp;amp;channel=%slug%&quot; RegEx=&quot;http://www.livestream.com/(?&amp;lt;Slug&amp;gt;.*)&quot; FormatHint=&quot;http://www.livestream.com/&amp;lt;slug&amp;gt;&quot; /&gt;
        ///  &lt;Provider xsi:typ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Providers {
            get {
                return ResourceManager.GetString("Providers", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap read_16 {
            get {
                object obj = ResourceManager.GetObject("read_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sc2_16 {
            get {
                object obj = ResourceManager.GetObject("sc2_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap settings_16 {
            get {
                object obj = ResourceManager.GetObject("settings_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stream_16 {
            get {
                object obj = ResourceManager.GetObject("stream_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Subscriptions xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Subscription xsi:type=&quot;Feed&quot; Name=&quot;WorldofWarcraft.com&quot; Url=&quot;http://us.battle.net/wow/en/feed/news&quot; /&gt;
        ///  &lt;Subscription xsi:type=&quot;Feed&quot; Name=&quot;Starcraft2.com&quot; Url=&quot;http://us.battle.net/sc2/en/feed/news&quot; /&gt;
        ///  &lt;Subscription xsi:type=&quot;Feed&quot; Name=&quot;MMO-Champion&quot; Url=&quot;http://www.mmo-champion.com/external.php?do=rss&amp;amp;type=newcontent&amp;amp;sectionid=1&amp;amp;days=120&amp;amp;count= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Subscriptions_Default {
            get {
                return ResourceManager.GetString("Subscriptions_Default", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap unread_16 {
            get {
                object obj = ResourceManager.GetObject("unread_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap update_16 {
            get {
                object obj = ResourceManager.GetObject("update_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap us_16 {
            get {
                object obj = ResourceManager.GetObject("us_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap video_16 {
            get {
                object obj = ResourceManager.GetObject("video_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wow_16 {
            get {
                object obj = ResourceManager.GetObject("wow_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
