//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlizzTV.Assets.i18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class i18n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal i18n() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlizzTV.Assets.i18n.i18n", typeof(i18n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Complete.
        /// </summary>
        internal static string DownloadComplete {
            get {
                return ResourceManager.GetString("DownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Failed.
        /// </summary>
        internal static string DownloadFailed {
            get {
                return ResourceManager.GetString("DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Adobe Flash Player.
        /// </summary>
        internal static string DownloadingAdobeFlashPlayer {
            get {
                return ResourceManager.GetString("DownloadingAdobeFlashPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Microsoft Visual C++ 2010 redistributable.
        /// </summary>
        internal static string DownloadingVisualCPP2010 {
            get {
                return ResourceManager.GetString("DownloadingVisualCPP2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adobe Flash Player download failed. Please install it manually..
        /// </summary>
        internal static string FlashPlayerDownloadFailedMessage {
            get {
                return ResourceManager.GetString("FlashPlayerDownloadFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlizzTV requires Abode Flash Player for best user-experience. Do you want to install latest version of Adobe Flash Player now?.
        /// </summary>
        internal static string FlashPlayerRequiredMessage {
            get {
                return ResourceManager.GetString("FlashPlayerRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing component: Adobe Flash Player.
        /// </summary>
        internal static string FlashPlayerRequiredTitle {
            get {
                return ResourceManager.GetString("FlashPlayerRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application will now exit to continue installation of Adobe Flash Player. Please restart BlizzTV after installation finishes..
        /// </summary>
        internal static string FlashPlayerWillBeInstalledMessage {
            get {
                return ResourceManager.GetString("FlashPlayerWillBeInstalledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Visual C++ 2010 redistributable download failed. Please install it manually..
        /// </summary>
        internal static string VisualCPP2010DownloadFailedMessage {
            get {
                return ResourceManager.GetString("VisualCPP2010DownloadFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlizzTV requires Microsoft Visual C++ 2010 redistributable package. Do you want to install it now?.
        /// </summary>
        internal static string VisualCPP2010RequiredMessage {
            get {
                return ResourceManager.GetString("VisualCPP2010RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing component: Microsoft Visual C++ 2010 Redistributable Package.
        /// </summary>
        internal static string VisualCPP2010RequiredTitle {
            get {
                return ResourceManager.GetString("VisualCPP2010RequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application will now exit to continue installation of Microsoft Visual C++ 2010 redistributable package. Please restart BlizzTV after installation finishes..
        /// </summary>
        internal static string VisualCPP2010WillBeInstalledMessage {
            get {
                return ResourceManager.GetString("VisualCPP2010WillBeInstalledMessage", resourceCulture);
            }
        }
    }
}
