//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlizzTV.Assets.i18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class i18n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal i18n() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlizzTV.Assets.i18n.i18n", typeof(i18n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter name for the new feed.
        /// </summary>
        internal static string AddNewFeedMessage {
            get {
                return ResourceManager.GetString("AddNewFeedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Feed.
        /// </summary>
        internal static string AddNewFeedTitle {
            get {
                return ResourceManager.GetString("AddNewFeedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter name for the new podcast.
        /// </summary>
        internal static string AddNewPodcastMessage {
            get {
                return ResourceManager.GetString("AddNewPodcastMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Podcast.
        /// </summary>
        internal static string AddNewPodcastTitle {
            get {
                return ResourceManager.GetString("AddNewPodcastTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields required.
        /// </summary>
        internal static string AllFieldsRequiredTitle {
            get {
                return ResourceManager.GetString("AllFieldsRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An alarm already exists for the event!.
        /// </summary>
        internal static string AnAlarmAlreadyExistsForEventMessage {
            get {
                return ResourceManager.GetString("AnAlarmAlreadyExistsForEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm exists.
        /// </summary>
        internal static string AnAlarmAlreadyExistsForEventTitle {
            get {
                return ResourceManager.GetString("AnAlarmAlreadyExistsForEventTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application will exit to continue installation of update. Please restart the application after..
        /// </summary>
        internal static string ApplicationWillExitToContinueInstallationOfUpdateMessage {
            get {
                return ResourceManager.GetString("ApplicationWillExitToContinueInstallationOfUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not de-activate modules that are currently updating. Please wait them finish and re-try..
        /// </summary>
        internal static string CanNotDeactivateUpdatingModules {
            get {
                return ResourceManager.GetString("CanNotDeactivateUpdatingModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlizzTV could not load one of it&apos;s required dependincies. Please re-install the program..
        /// </summary>
        internal static string CanNotLoadRequiredAssembliesMessage {
            get {
                return ResourceManager.GetString("CanNotLoadRequiredAssembliesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Error.
        /// </summary>
        internal static string CanNotLoadRequiredAssembliesTitle {
            get {
                return ResourceManager.GetString("CanNotLoadRequiredAssembliesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not setup an alarm for the event as it&apos;s just about to start.
        /// </summary>
        internal static string CanNotSetupEventAlarmMessage {
            get {
                return ResourceManager.GetString("CanNotSetupEventAlarmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not setup alarm.
        /// </summary>
        internal static string CanNotSetupEventAlarmTitle {
            get {
                return ResourceManager.GetString("CanNotSetupEventAlarmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to download server...
        /// </summary>
        internal static string ConnectingDownloadServer {
            get {
                return ResourceManager.GetString("ConnectingDownloadServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Complete.
        /// </summary>
        internal static string DownloadComplete {
            get {
                return ResourceManager.GetString("DownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded file is not a valid update. Please re-try downloading the update..
        /// </summary>
        internal static string DownloadedUpdateIsNotValidMessage {
            get {
                return ResourceManager.GetString("DownloadedUpdateIsNotValidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded file is not a valid update.
        /// </summary>
        internal static string DownloadedUpdateIsNotValidTitle {
            get {
                return ResourceManager.GetString("DownloadedUpdateIsNotValidTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download episode.
        /// </summary>
        internal static string DownloadEpisode {
            get {
                return ResourceManager.GetString("DownloadEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Failed.
        /// </summary>
        internal static string DownloadFailed {
            get {
                return ResourceManager.GetString("DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Adobe Flash Player.
        /// </summary>
        internal static string DownloadingAdobeFlashPlayer {
            get {
                return ResourceManager.GetString("DownloadingAdobeFlashPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Vista support files.
        /// </summary>
        internal static string DownloadingMSHtmlPIAForVista {
            get {
                return ResourceManager.GetString("DownloadingMSHtmlPIAForVista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading podcast episode: {0}.
        /// </summary>
        internal static string DownloadingPodcastEpisode {
            get {
                return ResourceManager.GetString("DownloadingPodcastEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading update: {0}.
        /// </summary>
        internal static string DownloadingUpdateTitle {
            get {
                return ResourceManager.GetString("DownloadingUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Microsoft Visual C++ 2010 redistributable.
        /// </summary>
        internal static string DownloadingVisualCPP2010 {
            get {
                return ResourceManager.GetString("DownloadingVisualCPP2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while loading your providers database. Please re-install the application to fix the problem..
        /// </summary>
        internal static string ErrorLoadingProvidersDatabaseMessage {
            get {
                return ResourceManager.GetString("ErrorLoadingProvidersDatabaseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Providers database load error.
        /// </summary>
        internal static string ErrorLoadingProvidersDatabaseTitle {
            get {
                return ResourceManager.GetString("ErrorLoadingProvidersDatabaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error parsing the feed. Please check the feed URL and retry..
        /// </summary>
        internal static string ErrorParsingFeedMessage {
            get {
                return ResourceManager.GetString("ErrorParsingFeedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing feed.
        /// </summary>
        internal static string ErrorParsingFeedTitle {
            get {
                return ResourceManager.GetString("ErrorParsingFeedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error parsing the podcast. Please check the podcast URL and retry..
        /// </summary>
        internal static string ErrorParsingPodcastMessage {
            get {
                return ResourceManager.GetString("ErrorParsingPodcastMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing podcast.
        /// </summary>
        internal static string ErrorParsingPodcastTitle {
            get {
                return ResourceManager.GetString("ErrorParsingPodcastTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error parsing the video channel. Please check the channel URL and retry..
        /// </summary>
        internal static string ErrorParsingVideoChannelMessage {
            get {
                return ResourceManager.GetString("ErrorParsingVideoChannelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing video channel.
        /// </summary>
        internal static string ErrorParsingVideoChannelTitle {
            get {
                return ResourceManager.GetString("ErrorParsingVideoChannelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress..
        /// </summary>
        internal static string EventInProgressMessage {
            get {
                return ResourceManager.GetString("EventInProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over..
        /// </summary>
        internal static string EventOverMessage {
            get {
                return ResourceManager.GetString("EventOverMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} to go..
        /// </summary>
        internal static string EventUpcomingMessage {
            get {
                return ResourceManager.GetString("EventUpcomingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An alarm is set for event {0} minutes before..
        /// </summary>
        internal static string ExistingAlarmMessage {
            get {
                return ResourceManager.GetString("ExistingAlarmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed downloading the update. Please try again later..
        /// </summary>
        internal static string FailedDownloadingTheUpdateMessage {
            get {
                return ResourceManager.GetString("FailedDownloadingTheUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update download failed!.
        /// </summary>
        internal static string FailedDownloadingTheUpdateTitle {
            get {
                return ResourceManager.GetString("FailedDownloadingTheUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feed already exists in your subscriptions named as &apos;{0}&apos;..
        /// </summary>
        internal static string FeedSubscriptionAlreadyExists {
            get {
                return ResourceManager.GetString("FeedSubscriptionAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill the feed name and URL fields!.
        /// </summary>
        internal static string FillFeedNameAndUrlFieldsMessage {
            get {
                return ResourceManager.GetString("FillFeedNameAndUrlFieldsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill the podcast name and URL fields!.
        /// </summary>
        internal static string FillPodcastNameAndUrlFieldsMessage {
            get {
                return ResourceManager.GetString("FillPodcastNameAndUrlFieldsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill the stream name and url fields!.
        /// </summary>
        internal static string FillStreamNameAndUrlFieldsMessage {
            get {
                return ResourceManager.GetString("FillStreamNameAndUrlFieldsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill the channel name and url fields!.
        /// </summary>
        internal static string FillVideoChannelNameAndUrlFieldsMessage {
            get {
                return ResourceManager.GetString("FillVideoChannelNameAndUrlFieldsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adobe Flash Player download failed. Please install it manually..
        /// </summary>
        internal static string FlashPlayerDownloadFailedMessage {
            get {
                return ResourceManager.GetString("FlashPlayerDownloadFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlizzTV requires Abode Flash Player for best user-experience. Do you want to install latest version of Adobe Flash Player now?.
        /// </summary>
        internal static string FlashPlayerRequiredMessage {
            get {
                return ResourceManager.GetString("FlashPlayerRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing component: Adobe Flash Player.
        /// </summary>
        internal static string FlashPlayerRequiredTitle {
            get {
                return ResourceManager.GetString("FlashPlayerRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application will now exit to continue installation of Adobe Flash Player. Please restart BlizzTV after installation finishes..
        /// </summary>
        internal static string FlashPlayerWillBeInstalledMessage {
            get {
                return ResourceManager.GetString("FlashPlayerWillBeInstalledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found a new available {0} version update. Do you want to update now?.
        /// </summary>
        internal static string FoundANewUpdateMessage {
            get {
                return ResourceManager.GetString("FoundANewUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New {0} update found!.
        /// </summary>
        internal static string FoundANewUpdateTitle {
            get {
                return ResourceManager.GetString("FoundANewUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing Update.
        /// </summary>
        internal static string InstallingUpdateTitle {
            get {
                return ResourceManager.GetString("InstallingUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is an invalid {1} url. Please correct the url and retry..
        /// </summary>
        internal static string InvalidStreamUrlMessage {
            get {
                return ResourceManager.GetString("InvalidStreamUrlMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL.
        /// </summary>
        internal static string InvalidUrl {
            get {
                return ResourceManager.GetString("InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is an invalid {1} url. Please correct the url and retry..
        /// </summary>
        internal static string InvalidVideoChannelUrlMessage {
            get {
                return ResourceManager.GetString("InvalidVideoChannelUrlMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark All As Read.
        /// </summary>
        internal static string MarkAllAsRead {
            get {
                return ResourceManager.GetString("MarkAllAsRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark All As Unread.
        /// </summary>
        internal static string MarkAllAsUnread {
            get {
                return ResourceManager.GetString("MarkAllAsUnread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark All As Unwatched.
        /// </summary>
        internal static string MarkAllAsUnwatched {
            get {
                return ResourceManager.GetString("MarkAllAsUnwatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark All As Watched.
        /// </summary>
        internal static string MarkAllAsWatched {
            get {
                return ResourceManager.GetString("MarkAllAsWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark As Read.
        /// </summary>
        internal static string MarkAsRead {
            get {
                return ResourceManager.GetString("MarkAsRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark As Unread.
        /// </summary>
        internal static string MarkAsUnread {
            get {
                return ResourceManager.GetString("MarkAsUnread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark As Unwatched.
        /// </summary>
        internal static string MarkAsUnwatched {
            get {
                return ResourceManager.GetString("MarkAsUnwatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark As Watched.
        /// </summary>
        internal static string MarkAsWatched {
            get {
                return ResourceManager.GetString("MarkAsWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module {0} is updating.
        /// </summary>
        internal static string ModuleUpdating {
            get {
                return ResourceManager.GetString("ModuleUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download failed for Windows Vista support files. Please install it manually and start the application after..
        /// </summary>
        internal static string MSHtmlPIAForVistaDownloadFailedMessage {
            get {
                return ResourceManager.GetString("MSHtmlPIAForVistaDownloadFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlizzTV requires support files (Primary Interopability Assemblies) to work on Windows Vista. It&apos;ll be downloaded now..
        /// </summary>
        internal static string MSHtmlPIAForVistaRequiredMessage {
            get {
                return ResourceManager.GetString("MSHtmlPIAForVistaRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing component: Support files for Windows Vista.
        /// </summary>
        internal static string MSHtmlPIAForVistaRequiredTitle {
            get {
                return ResourceManager.GetString("MSHtmlPIAForVistaRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded package will now be installed. .
        /// </summary>
        internal static string MSHtmlPIAForVistaWillBeInstalledMessage {
            get {
                return ResourceManager.GetString("MSHtmlPIAForVistaWillBeInstalledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re already running the latest version..
        /// </summary>
        internal static string NoAvailableUpdateFoundMessage {
            get {
                return ResourceManager.GetString("NoAvailableUpdateFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No available updates found.
        /// </summary>
        internal static string NoAvailableUpdateFoundTitle {
            get {
                return ResourceManager.GetString("NoAvailableUpdateFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The podcast already exists in your subscriptions named as &apos;{0}&apos;..
        /// </summary>
        internal static string PodcastSubscriptionAlreadyExists {
            get {
                return ResourceManager.GetString("PodcastSubscriptionAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-download episode.
        /// </summary>
        internal static string ReDownloadPodcastEpisode {
            get {
                return ResourceManager.GetString("ReDownloadPodcastEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaced your subscriptions database, it should be all working now..
        /// </summary>
        internal static string ReplacedSubscriptionsDatabaseMessage {
            get {
                return ResourceManager.GetString("ReplacedSubscriptionsDatabaseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriptions database replaced.
        /// </summary>
        internal static string ReplacedSubscriptionsDatabaseTitle {
            get {
                return ResourceManager.GetString("ReplacedSubscriptionsDatabaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the Murlocs!.
        /// </summary>
        internal static string SaveTheMurlocs {
            get {
                return ResourceManager.GetString("SaveTheMurlocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup alarm for event: {0}.
        /// </summary>
        internal static string SetupAlarmTitle {
            get {
                return ResourceManager.GetString("SetupAlarmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream is online, click to start watching it..
        /// </summary>
        internal static string StreamOnlineNotification {
            get {
                return ResourceManager.GetString("StreamOnlineNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream already exists in your subscriptions named as &apos;{0}&apos;..
        /// </summary>
        internal static string StreamSubscriptionAlreadyExistsMessage {
            get {
                return ResourceManager.GetString("StreamSubscriptionAlreadyExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription exists.
        /// </summary>
        internal static string SubscriptionExists {
            get {
                return ResourceManager.GetString("SubscriptionExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your subscriptions database is corrupted. Do you want it to be replaced with a default one?.
        /// </summary>
        internal static string SubscriptionsDatabaseCorruptedMessage {
            get {
                return ResourceManager.GetString("SubscriptionsDatabaseCorruptedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupted subscriptions database.
        /// </summary>
        internal static string SubscriptionsDatabsaeCorruptedTitle {
            get {
                return ResourceManager.GetString("SubscriptionsDatabsaeCorruptedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while update is being installed...
        /// </summary>
        internal static string UpdateIsBeingInstalledMessage {
            get {
                return ResourceManager.GetString("UpdateIsBeingInstalledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The channel already exists in your subscriptions named as &apos;{0}&apos;..
        /// </summary>
        internal static string VideoChannelSubscriptionsAlreadyExists {
            get {
                return ResourceManager.GetString("VideoChannelSubscriptionsAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Visual C++ 2010 redistributable download failed. Please install it manually..
        /// </summary>
        internal static string VisualCPP2010DownloadFailedMessage {
            get {
                return ResourceManager.GetString("VisualCPP2010DownloadFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlizzTV requires Microsoft Visual C++ 2010 redistributable package. Do you want to install it now?.
        /// </summary>
        internal static string VisualCPP2010RequiredMessage {
            get {
                return ResourceManager.GetString("VisualCPP2010RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing component: Microsoft Visual C++ 2010 Redistributable Package.
        /// </summary>
        internal static string VisualCPP2010RequiredTitle {
            get {
                return ResourceManager.GetString("VisualCPP2010RequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application will now exit to continue installation of Microsoft Visual C++ 2010 redistributable package. Please restart BlizzTV after installation finishes..
        /// </summary>
        internal static string VisualCPP2010WillBeInstalledMessage {
            get {
                return ResourceManager.GetString("VisualCPP2010WillBeInstalledMessage", resourceCulture);
            }
        }
    }
}
