//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlizzTV.Assets.Sounds {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Notifications {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Notifications() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlizzTV.Assets.Sounds.Notifications", typeof(Notifications).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] BabyMurloc {
            get {
                object obj = ResourceManager.GetObject("BabyMurloc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BattleCruisor {
            get {
                object obj = ResourceManager.GetObject("BattleCruisor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CreepTumor {
            get {
                object obj = ResourceManager.GetObject("CreepTumor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DefaultNotification {
            get {
                object obj = ResourceManager.GetObject("DefaultNotification", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DoorBell {
            get {
                object obj = ResourceManager.GetObject("DoorBell", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FastBells {
            get {
                object obj = ResourceManager.GetObject("FastBells", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Incomiiing {
            get {
                object obj = ResourceManager.GetObject("Incomiiing", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MasterYoda {
            get {
                object obj = ResourceManager.GetObject("MasterYoda", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Murloc {
            get {
                object obj = ResourceManager.GetObject("Murloc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Notice1 {
            get {
                object obj = ResourceManager.GetObject("Notice1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Notice2 {
            get {
                object obj = ResourceManager.GetObject("Notice2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Notice3 {
            get {
                object obj = ResourceManager.GetObject("Notice3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Notice4 {
            get {
                object obj = ResourceManager.GetObject("Notice4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Ping {
            get {
                object obj = ResourceManager.GetObject("Ping", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Polymorph {
            get {
                object obj = ResourceManager.GetObject("Polymorph", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ProtossAdvistor {
            get {
                object obj = ResourceManager.GetObject("ProtossAdvistor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PVPQueue {
            get {
                object obj = ResourceManager.GetObject("PVPQueue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SuperMario {
            get {
                object obj = ResourceManager.GetObject("SuperMario", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] TerranAdvisor {
            get {
                object obj = ResourceManager.GetObject("TerranAdvisor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Tetris {
            get {
                object obj = ResourceManager.GetObject("Tetris", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Tina {
            get {
                object obj = ResourceManager.GetObject("Tina", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] TinyBells {
            get {
                object obj = ResourceManager.GetObject("TinyBells", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Whisper {
            get {
                object obj = ResourceManager.GetObject("Whisper", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ZergEvolution {
            get {
                object obj = ResourceManager.GetObject("ZergEvolution", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
